### ISSUE TITLE
Fix ACP Packages Template wrt Term table

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#12]
Well !!! After further investigation ... There is a bug in `admin.js`...
To resolve this , you have 3 options :
1. turn the first table to `non-responsive`. {not recommended}
2. Add the `thead` to with `style="display: none;"` & wait till someone make a PR to fix that JS issue. { will take plenty of time }
3. Don't use table inside table , instead use `Div`. {recommended & also looks cool on desktop & Mobile devices}

Best regards 👍

**Comment by dark-1** [comment]
@stevotvr ,

if you prefer very close to table style then ,
Template file : 
```html
<td>
{% if p.term %}
	<div class="divtable">
		{% for t in p.term|slice(0, 4) %}
			<div class="divtr">
				<div class="divtd divtd1">{{ t.PRICE }}</div>
				<div class="divtd divtd2">{% if t.LENGTH %}{{ t.LENGTH }}{% else %}<i>{{ lang('ACP_GROUPSUB_EXPIRES_UNLIMITED') }}</i>{% endif %}</div>
			</div>
		{% endfor %}
		{% if p.term|length > 4 %}
			<div class="divtr divtrtd">{{ lang('ACP_GROUPSUB_MORE', p.term|length - 4) }}</div>
		{% endif %}
	</div>
{% endif %}
</td>
```

CSS file : 
```css
.divtable {
	border: 1px solid #000000;
	border-radius: 5px;
}

.divtr {
	border-bottom: 1px solid #000000;
}

.divtrtd {
	padding: 5px;
	display:block;
}

.divtd {
	padding: 5px;
	display:inline-block;
}

.divtd1 {
	width:50%;
}

.divtd2 {
	border-left: 1px solid #000000;
}
```

Best regards 👍
